Update buildapp.yml

diff --git a/.github/workflows/buildapp.yml b/.github/workflows/buildapp.yml
--- a/.github/workflows/buildapp.yml
+++ b/.github/workflows/buildapp.yml
@@ -131,6 +131,10 @@ jobs:
         run: |
           mkdir -p theos/lib/iphone/rootless
           cd ${{ github.workspace }}/main
+          if [ ! -f "Makefile" ]; then
+            echo "Error: Makefile not found in the main directory."
+            exit 1
+          fi
           sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
           sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
           make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
